# Generated by Django 5.2.1 on 2025-06-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0005_remove_userprofile_band_userprofile_venue_controlled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
